name: AKBC 2019
author: AKBC
baseurl: "akbc-testsite/"
description: "1st Conference on Automated Knowledge Base Construction"
email: "info@akbc.ws"


include: ["_pages"]

markdown: kramdown

# Plugins
gems:
- jekyll-sitemap
safe: false
